In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [ ]:
import pandas as pd
import glob

In [ ]:
f=sorted(glob.glob('/content/gdrive/My Drive/memes/*'))
f1=f[:1000]   #Take the first 1000

In [ ]:
from keras.preprocessing import image
from skimage import color
from skimage.feature import hog

In [ ]:
print(f1)

['/content/gdrive/My Drive/memes/2bvcu7.jpg', '/content/gdrive/My Drive/memes/2dxg4j.jpg', '/content/gdrive/My Drive/memes/2g0uu5.jpg', '/content/gdrive/My Drive/memes/2g54cq.png', '/content/gdrive/My Drive/memes/2jwc52.png', '/content/gdrive/My Drive/memes/2msrcz.jpg', '/content/gdrive/My Drive/memes/2niehv.jpg', '/content/gdrive/My Drive/memes/2ugt2n.jpg', '/content/gdrive/My Drive/memes/2wod3h.png', '/content/gdrive/My Drive/memes/2x430e.jpg', '/content/gdrive/My Drive/memes/2x5zai.jpg', '/content/gdrive/My Drive/memes/34fi1c.png', '/content/gdrive/My Drive/memes/38pgb7.jpg', '/content/gdrive/My Drive/memes/3bbaa4.png', '/content/gdrive/My Drive/memes/3br74t.jpg', '/content/gdrive/My Drive/memes/3o00ad.jpg', '/content/gdrive/My Drive/memes/3vurw8.jpg', '/content/gdrive/My Drive/memes/3x3bqx.jpg', '/content/gdrive/My Drive/memes/4c12i4.png', '/content/gdrive/My Drive/memes/4g5t0v.jpg', '/content/gdrive/My Drive/memes/4hvmad.jpg', '/content/gdrive/My Drive/memes/4l0c7e.jpg', '/content

In [ ]:
ls=[]
for x in f1:
  img = image.load_img(x,target_size=(224, 224))
  arr=image.img_to_array(img)
  data_gray =color.rgb2gray(arr)
  ls.append(data_gray)

In [ ]:
len(ls)

1000

In [ ]:
ppc = 32
hog_images = []
hog_features = []
for x in ls:
    feature_vec,image = hog(x, orientations=8, pixels_per_cell=(ppc,ppc),cells_per_block=(4, 4),block_norm= 'L2',visualise=True)
    hog_images.append(image)
    print(image)
    hog_features.append(feature_vec)

In [ ]:
import numpy as np
hog_features=np.array(hog_features)

In [ ]:
hog_features.shape


(1000, 2048)

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
kmeans = KMeans(n_clusters=3, random_state=0)
cl=kmeans.fit_predict(hog_features)
print(cl)

[2 1 1 1 0 2 1 1 2 1 2 0 2 2 1 2 0 1 0 2 1 1 1 2 1 1 1 2 0 1 2 2 2 2 0 2 1
 2 1 1 1 0 0 2 0 1 1 0 1 2 1 1 2 1 2 1 0 0 0 1 0 2 0 2 0 0 2 1 0 2 2 1 1 2
 0 1 1 0 1 1 1 2 0 0 1 2 2 0 0 0 1 2 1 2 2 2 1 2 0 0 0 2 1 0 1 2 1 0 0 0 0
 0 0 1 2 1 1 0 0 2 0 1 0 0 2 0 2 2 2 2 0 2 1 0 2 2 0 0 0 1 0 0 2 1 2 2 1 0
 1 0 1 0 1 1 1 0 0 2 1 0 1 2 0 0 0 0 1 1 1 2 1 0 0 1 2 0 0 0 0 1 1 0 0 0 2
 0 0 0 2 1 2 0 0 2 0 0 2 0 2 1 2 0 0 0 1 2 0 0 0 0 2 2 0 0 2 0 0 1 0 1 0 0
 0 1 1 0 0 2 0 0 0 2 2 1 1 0 1 2 0 0 1 1 0 1 1 2 1 2 0 0 0 2 0 1 1 0 0 1 2
 1 2 0 1 0 0 1 0 0 0 0 0 0 1 0 2 1 0 0 2 0 1 1 2 0 0 0 0 0 0 0 0 2 2 2 0 2
 1 0 1 0 2 2 0 1 2 0 0 0 2 0 0 1 1 1 2 1 1 1 0 1 2 2 2 2 2 2 0 2 2 1 0 1 0
 0 0 2 0 1 0 1 1 2 0 0 1 0 2 0 0 2 1 0 2 2 1 1 2 0 2 2 0 2 1 1 2 0 1 0 0 2
 1 0 1 0 0 2 0 0 0 2 0 2 1 2 1 2 0 0 0 2 0 2 1 1 2 0 2 0 2 1 1 0 0 2 2 0 0
 0 1 0 0 0 1 1 1 0 0 1 0 1 1 2 0 0 2 0 1 0 0 0 2 1 0 2 0 0 0 0 0 1 0 0 0 1
 0 1 2 0 1 1 2 0 1 2 0 0 1 1 0 2 0 0 0 1 2 2 2 1 0 0 0 0 0 1 0 1 2 2 1 0 1
 1 1 0 2 0 1 0 1 2 0 0 1 

In [ ]:
import numpy as np
np.savetxt("/content/gdrive/My Drive/clusters_hog.csv", kmeans, delimiter=",")

In [ ]:
from keras.preprocessing import image
x=f[1001]
n=5
print(x)
ppc = 32
hog_images = []
hog_features = []
import numpy as np
img = image.load_img(x,target_size=(224, 224))
arr=image.img_to_array(img)
data_gray =color.rgb2gray(arr)
feature_vec,image = hog(data_gray, orientations=8, pixels_per_cell=(ppc,ppc),cells_per_block=(4, 4),block_norm= 'L2',visualise=True)
hog_images.append(image)
print(image)
hog_features.append(feature_vec)
hog_features=np.array(hog_features)
cid=kmeans.predict(hog_features)
print(cid)
g=np.array(f)
h=(cl==cid[0])
print(type(h))
h=list(h)
ind=[i for i,x in enumerate(h) if x==True]
print(g[np.array(ind)][:n])


/content/gdrive/My Drive/memes/6ul56t.jpg
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[1]
<class 'numpy.ndarray'>
['/content/gdrive/My Drive/memes/2dxg4j.jpg'
 '/content/gdrive/My Drive/memes/2g0uu5.jpg'
 '/content/gdrive/My Drive/memes/2g54cq.png'
 '/content/gdrive/My Drive/memes/2niehv.jpg'
 '/content/gdrive/My Drive/memes/2ugt2n.jpg']


/usr/local/lib/python3.6/dist-packages/skimage/feature/_hog.py:239: skimage_deprecation: Argument `visualise` is deprecated and will be changed to `visualize` in v0.16
  'be changed to `visualize` in v0.16', skimage_deprecation)
